### ISSUE TITLE
does openshmem project require signing a collaborators agreement?

### ISSUE THREAD

**Issue by hppritcha** [openshmem-org/openshmem#14]
Some projects like Open MPI and Open UCX require that an organization/individual sign a collaborators agreement in order to contribute to the project.

Does the Open SHMEM project have a similar collaborators agreement?

**Comment by shamisp** [comment]
@hppritcha - AFAIK the answer is yes. You may poke JeffK about this.

**Comment by hppritcha** [comment]
I think this can be closed.
